config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { sessions: 'users/sessions', :registrations => "users/registrations",
                                      :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    collection do
      get :news_feed
      get :profile
      get :search
    end
    member do
      post :upload_pic
      get :profile
    end
    resources :dream_garages, only: [:create, :destroy]
  end
  
  resources :companies do
    member do
      post :upload_pic 
    end
  end

  resources :groups do
    member do
      post :upload_pic 
    end
  end

  resources :events do
    member do
      post :attend
      post :drop
      post :join_request
      put :accept_request
      get :accept_invitation
      post :send_invitations
      post :upload_pic
    end
  end

  resources :motors do
    collection do
      get :look_up, constraints: { format: 'json' }
    end
    member do
      post :upload_pic
    end
  end

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :posts, only: [:create, :show] do
    member do
      post :like
      post :dislike
      post :create_comment
      post :add_reply
      post :like_comment
      post :dislike_comment
    end

    resource :comments, only: %i[destroy]
  end


  resources :settings, only: [] do
    collection do
      match '/account' => 'settings#account', via: [:get, :post]
      match '/privacy' => 'settings#privacy', via: [:get, :post]
      match '/notifications' => 'settings#notifications', via: [:get, :post]
      match '/security' => 'settings#security', via: [:get, :post]
    end
  end

  resources :utils, only: [] do
    collection do
      get :states_list
      get :cities_list
      get :location_search
    end
  end

  resources :follow, only: [] do
    collection do
      post :user
      post :unfollow_user
      post :motor
      post :unfollow_motor
      post :company
      post :unfollow_company
    end
  end

  resources :notifications, only: [:index] do

  end

  resource :search, controller: 'search', only: [] do
    collection do
      get :people
      get :companies
      get :motors
      get :groups
      get :events
    end
  end

  get '/publish/:type', to: 'posts#new', as: :publish_blog
  get '/news_feed', to: 'users#news_feed', as: :news_feed
  get '/profile', to: 'users#profile', as: :user_profile
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def people
    @results = AdvancedSearch.search_users(params)
  end

  def companies
    @results = AdvancedSearch.search_companies(params)
  end

  def motors
    @results = AdvancedSearch.search_motors(params)
  end

  def groups
    @results = AdvancedSearch.search_groups(params)
  end

  def events
    @results = AdvancedSearch.search_events(params)
  end

  private
  
end

app/helpers/search_helper.rb
module SearchHelper

  def search_tab_active_klass(name)
    'active' if action_name.eql?(name)
  end
end

app/views/search/_search_box_container.html.erb
<div class="content-container mobile-order-1">
  <div class="content-block">
    <div class="block-body">
      <%= form_tag(form_action, class: 'form content-form', method: :get, id: 'search_form') do %>
        <div class="form-group search-group">
          <label for="keywordSearch">Keywords search</label>
          <div>
            <input type="text" name='term' value="<%= params[:term] %>" id="keywordSearch" class="form-control" placeholder="Type search keywords">
            <span class="form-control-border"></span>
              <a href="javascript:{}" onclick="document.getElementById('search_form').submit();" role="button" class="search-btn">
                <span class="zmdi zmdi-search"></span>
              </a>
          </div>
        </div>
      <% end %>
    </div>
    <div class="tabs-container page-control-tabs">
      <ul class="nav nav-tabs content-tabs justify-content-center" id="SearchTab" role="tablist">
        <li class="nav-item">
          <a class="nav-link <%= search_tab_active_klass('companies') %>" href="/search/companies"  data-behavior='update_search_action'>Company</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <%= search_tab_active_klass('people') %>" href="/search/people" data-behavior='update_search_action'>People</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <%= search_tab_active_klass('motors') %>" href="/search/motors" data-behavior='update_search_action'>Motors</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <%= search_tab_active_klass('groups') %>" href="/search/groups" data-behavior='update_search_action'>Groups</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <%= search_tab_active_klass('events') %>" href="/search/events" data-behavior='update_search_action'>Events</a>
        </li>
      </ul>
      <div class="select-container">
        <span class="label">Search in category:</span>
        <select class="selectpicker" id="pageControlTabs">
          <option data-tokens="0" value="company">Company</option>
          <option data-tokens="1" value="people">People</option>
          <option data-tokens="2" value="motors">Motors</option>
          <option data-tokens="3" value="groups">Groups</option>
          <option data-tokens="4" value="events">Events</option>
        </select>
      </div>
    </div>
  </div>
</div>

app/views/search/companies.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="main-container">
        <%= render partial: 'search/advanced_search/companies' %>
        <%= render partial: 'search/search_box_container', locals: { form_action: companies_search_path} %>  
        <div class="content-container mobile-order-3">
          <div class="content-block">
            <div class="block-header">
              <h4 class="with-icon"><i class="zmdi zmdi-city"></i>Company</h4>
              <a href="#" class="link">See all</a>
            </div>
            <div class="block-body">
              <div class="content-items-list full-width">
                <% @results.each do |company| %>
                  <div class="item">
                    <%= link_to company_path(company.id), class: 'avatar-container', target: '_blank' do %>
                      <%= image_tag company.thumb_url, alt: '' %>
                    <% end %>
                    <div class="info">
                      <%= link_to company.name, company_path(company.id), class: 'title', target: '_blank' %>
                      <span class="location"><i class="zmdi zmdi-pin"></i><span><%= company.city %></span></span>
                    </div>
                    <div class="buttons-container">
                      <% if current_user.follow_company?(company) %>
                        <%= link_to unfollow_company_follow_index_path(id: company.id), method: :post, target: '_blank', class: 'btn btn-primary btn-follow' do %>
                          <span>UnFollow</span>
                        <% end %>
                      <% else %>
                        <%= link_to company_follow_index_path(id: company.id), method: :post, target: '_blank', class: 'btn btn-primary btn-follow' do %>
                          <span>Follow</span>
                        <% end %>
                      <% end %>
                      <a href="#" class="btn btn-secondary btn-more"><i class="zmdi zmdi-more"></i></a>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="block-footer">
              <a href="#" class="more-block-btn"><i class="zmdi zmdi-more"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/search/events.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="main-container">
        <%= render partial: 'search/advanced_search/events' %>
        <%= render partial: 'search/search_box_container', locals: { form_action: events_search_path} %>
        <div class="content-container mobile-order-3">
          <div class="content-block">
            <div class="block-header">
              <h4 class="with-icon"><i class="zmdi zmdi-calendar-note"></i>Events</h4>
              <a href="#" class="link">See all</a>
            </div>
            <div class="block-body">
              <div class="content-items-list full-width">
                <% @results.each do |event| %>
                  <div class="item">
                    <%= link_to event_path(event.id), class: 'avatar-container', target: '_blank' do %>
                      <%= image_tag event.thumb_url, alt: '' %>
                    <% end %>
                    <div class="info">
                      <%= link_to event.name, event_path(event.id), class: 'title', target: '_blank' %>
                      <span class="location"><i class="zmdi zmdi-pin"></i><span><%= event.city %></span></span>
                    </div>
                    <div class="buttons-container">
                      <% unless event.admin_users.include?(current_user) %>
                        <% if event.attendees.include?(current_user) %>
                          <%= link_to drop_event_path(event), method: :post, class: 'btn btn-primary', target: '_blank' do %>
                            <span>Drop from Event</span>
                          <% end %>
                        <% elsif event.has_pending_invitation?(current_user) %>
                          <%= link_to accept_invitation_event_path(event), class: 'btn btn-primary', target: '_blank' do %>
                            <span>Accept Invitation</span>
                          <% end %>
                        <% elsif event.public? %>
                          <%= link_to attend_event_path(event), method: :post, class: 'btn btn-primary', target: '_blank' do %>
                            <span>Attend Event</span>
                          <% end %>
                        <% elsif event.on_request? %>
                          <%= link_to join_request_event_path(event), method: :post, class: 'btn btn-primary', target: '_blank' do %>
                            <span>Request to Attend</span>
                          <% end %>
                        <% end %>
                      <% end %>
                      <a href="#" class="btn btn-secondary btn-more"><i class="zmdi zmdi-more"></i></a>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="block-footer">
              <a href="#" class="more-block-btn"><i class="zmdi zmdi-more"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/search/groups.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="main-container">
        <%= render partial: 'search/advanced_search/groups' %>
        <%= render partial: 'search/search_box_container', locals: { form_action: groups_search_path} %>  
        <div class="content-container mobile-order-3">
          <div class="content-block">
            <div class="block-header">
              <h4 class="with-icon"><i class="zmdi zmdi-accounts-alt"></i>Groups</h4>
              <a href="#" class="link">See all</a>
            </div>
            <div class="block-body">
              <div class="content-items-list full-width">
                <% @results.each do |group| %>
                  <div class="item">
                    <%= link_to group_path(group), class: 'avatar-container', target: '_blank' do %>
                      <%= image_tag group.thumb_url, alt: '' %>
                    <% end %>
                    <div class="info">
                      <%= link_to group.name, group_path(group), class: 'title', target: '_blank' %>
                      <!-- <span class="location"><i class="zmdi zmdi-pin"></i><span>London</span></span> -->
                    </div>
                    <div class="buttons-container">
                      <a href="#" class="btn btn-primary btn-follow"><span>Join group</span></a>
                      <a href="#" class="btn btn-secondary btn-more"><i class="zmdi zmdi-more"></i></a>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="block-footer">
              <a href="#" class="more-block-btn"><i class="zmdi zmdi-more"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/search/people.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="main-container">
        <%= render partial: 'search/advanced_search/people' %>
        <%= render partial: 'search/search_box_container', locals: { form_action: people_search_path} %>  
        <div class="content-container mobile-order-3">
          <div class="content-block">
            <div class="block-header">
              <h4 class="with-icon"><i class="zmdi zmdi-account"></i>People</h4>
              <a href="#" class="link">See all</a>
            </div>
            <div class="block-body">
              <div class="content-items-list full-width">
                <% @results.each do |user| %>
                  <div class="item">
                    <%= link_to profile_user_path(user.id), class: 'avatar-container', target: '_blank' do %>
                      <%= image_tag user.thumb_url, alt: '' %>
                    <% end %>
                    <div class="info">
                      <%= link_to user.display_name, profile_user_path(user.id), class: 'title', target: '_blank' %>
                      <span class="location"><i class="zmdi zmdi-pin"></i><span><%= user.city %></span></span>
                    </div>
                    <div class="buttons-container">
                      <% if current_user.follow_user?(user) %>
                        <%= link_to unfollow_user_follow_index_path(id: user.id), method: :post, class: 'btn btn-primary' do %>
                          <span>UnFollow</span>
                        <% end %>
                      <% else %>
                        <%= link_to user_follow_index_path(id: user.id), method: :post, class: 'btn btn-primary' do %>
                          <span>Follow</span>
                        <% end %>
                      <% end %>
                      <a href="#" class="btn btn-secondary btn-more"><i class="zmdi zmdi-more"></i></a>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
            <div class="block-footer">
              <a href="#" class="more-block-btn"><i class="zmdi zmdi-more"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>