config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { sessions: 'users/sessions', :registrations => "users/registrations",
                                      :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    collection do
      get :news_feed
      get :profile
      get :search
    end
    member do
      post :upload_pic
      get :profile
    end
    resources :dream_garages, only: [:create, :destroy]
  end
  
  resources :companies do
    member do
      post :upload_pic 
    end
  end

  resources :groups do
    member do
      post :upload_pic 
    end
  end

  resources :events do
    member do
      post :attend
      post :drop
      post :join_request
      put :accept_request
      get :accept_invitation
      post :send_invitations
      post :upload_pic
    end
  end

  resources :motors do
    collection do
      get :look_up, constraints: { format: 'json' }
    end
    member do
      post :upload_pic
    end
  end

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :posts, only: [:create, :show] do
    member do
      post :like
      post :dislike
      post :create_comment
      post :add_reply
      post :like_comment
      post :dislike_comment
    end

    resource :comments, only: %i[destroy]
  end


  resources :settings, only: [] do
    collection do
      match '/account' => 'settings#account', via: [:get, :post]
      match '/privacy' => 'settings#privacy', via: [:get, :post]
      match '/notifications' => 'settings#notifications', via: [:get, :post]
      match '/security' => 'settings#security', via: [:get, :post]
    end
  end

  resources :utils, only: [] do
    collection do
      get :states_list
      get :cities_list
      get :location_search
    end
  end

  resources :follow, only: [] do
    collection do
      post :user
      post :unfollow_user
      post :motor
      post :unfollow_motor
      post :company
      post :unfollow_company
    end
  end

  resources :notifications, only: [:index] do

  end

  resource :search, controller: 'search', only: [] do
    collection do
      get :people
      get :companies
      get :motors
      get :groups
      get :events
    end
  end

  get '/publish/:type', to: 'posts#new', as: :publish_blog
  get '/news_feed', to: 'users#news_feed', as: :news_feed
  get '/profile', to: 'users#profile', as: :user_profile
end

app/models/entities/group.rb
class Group < Entity

  field :group_type, type: Integer, default: 0 # 0 -> Open, 1 -> by_request, 2 -> private
  
  validates :group_type, inclusion: { in: [0, 1, 2] }
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :get_group, only: [:show, :upload_pic, :edit, :update]

  def new
    @group = current_user.groups.build
  end

  def upload_pic
    if @group.update_attributes(group_pic_attrs)
      flash[:success] = "Updated pic successfully"
    else
      flash[:error] = "Failed to update pic"
    end
    redirect_to group_path(@group)
  end

  def create
    puts "*"*100
    puts params
    puts "*"*100
    group = current_user.groups.build(group_attrs)
    if group.save
      flash[:success] = 'Group Created successfully'
      set_current_entity(group)
      redirect_to group_path(group)
    else
      render_with_error(group.errors.full_messages.join(','), 422)
    end
  end

  def edit
    set_current_entity(@group)
  end

  def update
    if @group.update_attributes(group_attrs)
      flash[:success] = "Updated group profile successfully"
      redirect_to group_path(@group)
    else
      flash[:error] = "Failed to update profile"
      puts @group.errors.full_messages
    end
  end

  def show
    set_current_entity(@group)
  end

  private

  def group_attrs
    params.require(:group).permit(:group_type,
      profile_attributes: [:name, :about, :avatar, :cover_pic],
      photos_attributes: [:id, :file, :_destroy],
      categories_attributes: [:name, :make, :model]
    )
  end

  def group_pic_attrs
    params.require(:group).permit(
      profile_attributes: [:cover_pic, :avatar]
    )
  end

  def get_group
    @group ||= current_user.groups.find(params[:id])
  end
end

app/views/groups/_about.html.erb
<div class="tab-pane fade" id="about" role="tabpanel" aria-labelledby="aboutTab">
  <div class="main-container">
    <%= render partial: 'sidebar_container' %>
    <div class="content-container mobile-order-1">
      <div class="content-block article article-short description">
        <div class="article-header">
          <h3>About Group</h3>
        </div>
        <div class="article-body with-padding">
          <div class='notes'>
            <p class='short-note'>
              <%= truncate(@group.about, length: 350, omission: '', escape: false) { link_to '&nbsp;<i class="fa fa-long-arrow-right" aria-hidden="true"></i><span>Read More</span>'.html_safe, '#', 'data-behavior': 'read_more'} %>
            </p>
            <p class='full-note hidden'>
              <%= @group.about %>
              <br/>
              <%= link_to 'read less', '#', 'data-behavior': 'read_less' %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/groups/_all_posts.html.erb
<div class="tab-pane fade show active" id="allPosts" role="tabpanel" aria-labelledby="allPostsTab">
  <div class="main-container">
    <%= render partial: 'sidebar_container' %>
    <div class="content-container mobile-order-1">
      <div class="content-block article article-short description">
        <div class="article-header">
          <h3>About Group</h3>
        </div>
        <div class="article-body with-padding">
          <div class='notes'>
            <p class='short-note'>
              <%= truncate(@group.about, length: 350, omission: '', escape: false) { link_to '&nbsp;<i class="fa fa-long-arrow-right" aria-hidden="true"></i><span>Read More</span>'.html_safe, '#', 'data-behavior': 'read_more'} %>
            </p>
            <p class='full-note hidden'>
              <%= @group.about %>
              <br/>
              <%= link_to 'read less', '#', 'data-behavior': 'read_less' %>
            </p>
          </div>
        </div>
      </div>
    </div>
    <div class="content-container mobile-order-2">
      <%= render partial: 'entities/image_slider', locals: { parent: 'allPosts', photos: @group.photos, type: 'group' } %>
      <%= render partial: 'posts/add_post', locals: { target: '#allPosts .mobile-order-2' } %>
    </div>
    <div class="content-container mobile-order-3">
      <%= render partial: 'posts/index', locals: { posts: current_entity.posts } %>
    </div>
  </div>
</div>

app/views/groups/_list_groups.html.erb
<div class="widget-items-list">
  <% groups.each do |group| %>
    <div class="item boxed-item">
      <a class="avatar-container" href="#">
        <%= image_tag group.thumb_url, class: 'avatar-img', alt: group.name %>
      </a>
      <div class="info-container">
        <%= link_to group.name, group_path(group), class: 'item-title' %>
        <span class="item-description"><a href="#">Susan Smith</a> and <a href="#">644</a> joined group</span>
      </div>
    </div>
  <% end %>
  <% if groups.count == 0 %>
    <div class="item boxed-item">
      <p>No groups available </p>
    </div>
  <% end %>
</div>
<a href="#" class="link-more">See More</a>

app/views/groups/_main_container.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="tab-content" id="myTabContent">
        <%= render partial: 'about' %>
        <%= render partial: 'all_posts' %>
        <%= render partial: 'shared/photos_tab', locals: { photos: @group.photos } %>
        <%= render partial: 'shared/videos_tab', locals: { videos: @group.videos } %>
        <%= render partial: 'shared/blogs_tab' %>
      </div>
    </div>
  </div>
</div>

<footer class="footer">
</footer>

<div class="mobile-menu">
  <ul>
    <li>
      <a href="http://motor.valeda.co/login.html"><i class="ion-ios-home-outline"></i></a>
    </li>
    <li>
      <a href="http://motor.valeda.co/my_profile.html"><i class="ion-ios-person-outline"></i></a>
    </li>
    <li class="active">
      <a href="http://motor.valeda.co/settings.html"><i class="ion-ios-gear-outline"></i></a>
    </li>
    <li class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <a href="#"><i class="ion-ios-list-outline"></i></a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton1">
        <div class="dropdown-body">
          <a class="dropdown-item" href="http://motor.valeda.co/add_company.html">Create company profile</a>
          <a class="dropdown-item" href="http://motor.valeda.co/add_event.html">Create event</a>
          <a class="dropdown-item" href="http://motor.valeda.co/add_group.html">Create group</a>
        </div>
      </div>
    </li>
  </ul>
</div>

app/views/groups/_members_widget.html.erb
<div class="widget collapsible-widget">
  <div class="widget-header">
    <span class="title with-icon"><i class="zmdi zmdi-accounts-alt"></i>Members</span>
  </div>
  <div class="widget-body">
    <div class="options">
      <span>Latest Members</span>
      <a href="#">See All</a>
    </div>
    <div class="widget-items-list">
      <div class="item boxed-item">
        <a href="#" class="avatar-container">
          <img class="avatar-img" src="images/avatars/user-15-avatar.jpg" alt="">
        </a>
        <div class="info-container">
          <a href="#" class="item-title">William Hummingbird</a>
        </div>
      </div>
      <div class="item boxed-item" href="#">
        <a href="#" class="avatar-container">
          <img class="avatar-img" src="images/avatars/user-16-avatar.jpg" alt="">
        </a>
        <div class="info-container">
          <a href="#" class="item-title">Diana Wayne-Johnson</a>
        </div>
      </div>
    </div>
    <div class="buttons-container mt-20">
      <button data-toggle="modal" data-target="#manageUsers" class="btn btn-primary btn-block btn-small"><span>Manage users</span></button>
    </div>
  </div>
</div>

app/views/groups/_my_groups.html.erb
<div class="widget collapsible-widget my-groups-widget">
  <div class="widget-header">
    <span class="title with-icon"><i class="zmdi zmdi-accounts-alt"></i>My Groups</span>
  </div>
  <div class="widget-body">
    <%= render partial: 'groups/list_groups', locals: { groups: groups } %>
    <% if @user == current_user %>
      <div class="buttons-container">
        <%= link_to new_group_path, class: 'btn btn-primary btn-block btn-small' do %>
          <span>Create a group</span>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/_recommonded.html.erb
<div class="widget collapsible-widget recommonded-groups-widget">
  <div class="widget-header">
    <span class="title with-icon"><i class="zmdi zmdi-accounts-alt"></i>Recommended Groups</span>
  </div>
  <div class="widget-body">
    <%= render partial: 'groups/list_groups', locals: { groups: @user.groups } %>
  </div>
</div>

app/views/groups/_sidebar_container.html.erb
<div class="sidebar-container mobile-order-2">
  <div class="widget collapsible-widget">
    <div class="widget-header">
      <span class="title with-icon"><i class="zmdi zmdi-account-calendar"></i>Group Admins</span>
    </div>
    <div class="widget-body">
      <div class="widget-items-list">
        <div class="item boxed-item">
          <a href="#" class="avatar-container">
            <img class="avatar-img" src="images/avatars/user-13-avatar.jpg" alt="">
          </a>
          <div class="info-container">
            <a href="#" class="item-title">Alfred Steinberg</a>
          </div>
        </div>
      </div>
      <div class="buttons-container mt-20">
        <button data-toggle="modal" data-target="#manageAdmins" class="btn btn-primary btn-block btn-small"><span>Manage admins</span></button>
      </div>
    </div>
  </div>

  <%= render partial: 'entities/select_entity_type', locals: { entity: @group, type: 'group', field_name: 'group[group_type]' } %>
  <%= render partial: 'entities/category_widget', locals: { entity: @group, type: 'group' } %>
  <%= render partial: 'members_widget' %>
  <%= render partial: 'shared/sidebar_footer' %>
</div>

app/views/groups/edit.html.erb
<%= form_for(@group, method: :put, multipart: true, html: {class: 'form content-form', id: 'edit_group'}, remote: true) do |f| %>
  <%= render partial: 'entities/cover_pic_container', locals: { type: 'group', current: @group } %>
  <div class='container error'></div>

  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="main-container">
          <%= render partial: 'groups/sidebar_container' %>
          <div class="content-container mobile-order-1">
            <div class="content-block">
              <div class="block-header">
                <h4>About Group</h4>
              </div>
              <div class="block-body">
                <span class="description">Group details</span>
                <div class="form-group">
                  <%= text_area_tag 'group[profile_attributes][about]', @group.about, class: 'form-control', rows: 4, cols: 30 %>
                  <span class="form-control-border"></span>
                </div>
              </div>
            </div>
            <%= render partial: 'entities/categories_block', locals: { f: f, type: 'group', current: @group } %>
          </div>
          <div class="content-container mobile-order-3">
            <%= render partial: 'entities/upload_photos_and_videos_section', locals: { type: 'group', current: @group } %>
            <div class="buttons-block">
              <div class='hidden_images hidden'></div>
              <%= submit_tag "Update Group", class: 'btn btn-primary btn-block' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/groups/new.html.erb
<%= form_tag(groups_path, method: :post, multipart: true, class: 'form content-form', id: 'new_group', remote: true) do %>
  <%= render partial: 'entities/cover_pic_container', locals: { type: 'group', current: nil } %>
  <div class='container error'></div>

  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="main-container">
          <%= render partial: 'groups/sidebar_container' %>
          <div class="content-container mobile-order-1">
            <div class="content-block">
              <div class="block-header">
                <h4>About Group</h4>
              </div>
              <div class="block-body">
                <span class="description">Group details</span>
                <div class="form-group">
                  <%= text_area_tag 'group[profile_attributes][about]', '', class: 'form-control', rows: 4, cols: 30 %>
                  <span class="form-control-border"></span>
                </div>
              </div>
            </div>
            <%= render partial: 'entities/categories_block', locals: { type: 'group', current: nil } %>
          </div>
          <div class="content-container mobile-order-3">
            <%= render partial: 'entities/upload_photos_and_videos_section', locals: { type: 'group', current: nil } %>
            <div class="buttons-block">
              <div class='hidden_images hidden'></div>
              <%= submit_tag "Create Group", class: 'btn btn-primary btn-block' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/groups/show.html.erb
<div class="cover-image-container">
  <div class="cover-image-wrapper" style="background-image: url('<%= @group.cover_pic.url %>')">
    <div class="overlay"></div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="profile-page-heading">
          <div class="user-profile-info">
            <% if @group.user == current_user %>
              <%= link_to edit_group_path(@group) do %>
                <span class="btn btn-primary" style="position: absolute; left: 0; top: -105px;">EDIT</span>
              <% end %>
              <%= form_tag(upload_pic_group_path(@group), method: :post, multipart: true, class: 'form content-form') do %>
                <%= file_field_tag "group[profile_attributes][cover_pic]", class: 'hidden', id: "group_cover_pic", 'data-behavior': 'submit_form' %>
                  <label for='group_cover_pic'>
                    <span class="change-cover-image-btn btn btn-primary">
                      <span>Change cover</span>
                    </span>
                  </label>
              <% end %>
            <% end %>          
            <div class="avatar-container">
              <%= image_tag(@group.avatar.thumb.url, class: 'avatar-img') %>
              <% if @group.user == current_user %>
                <%= form_tag(upload_pic_group_path(@group), method: :post, multipart: true, class: 'form content-form') do %>
                  <%= file_field_tag "group[profile_attributes][avatar]", class: 'hidden', 'data-behavior': 'submit_form', id: 'group_profile_pic' %>
                  <label for='group_profile_pic'>
                    <span class="add-avatar">
                      <i class="zmdi zmdi-camera-add"></i>
                    </span>
                  </label>
                <% end %>
              <% end %> 
            </div>
            <div class="profile-info">
              <span class="user-name"><%= @group.name %></span>
              <!-- <span class="location"><i class="zmdi zmdi-pin"></i><%#=  @group.address.city %></span> -->
            </div>
            <div class="profile-stats">
              <ul class="stats-list">
                <li>
                  <span class="stats-counter">0</span>
                  <span class="stats-title">Members</span>
                </li>
                <li>
                  <span class="stats-counter">0</span>
                  <span class="stats-title">Page Views</span>
                </li>
                <li>
                  <span class="stats-counter">0</span>
                  <span class="stats-title">Posts</span>
                </li>
                <li>
                  <span class="stats-counter">0</span>
                  <span class="stats-title">Photos</span>
                </li>
              </ul>
            </div>
            <div class="profile-buttons">
              <a href="#" class="btn btn-primary"><span>Join Group</span></a>
            </div>
          </div>
          <div class="tabs-container page-control-tabs">
            <ul class="nav nav-tabs content-tabs justify-content-center" id="NewsfeedTab" role="tablist">
              <li class="nav-item">
                <a class="nav-link" id="aboutTab" data-toggle="tab" href="#about" role="tab" aria-controls="about" aria-expanded="true">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" id="allPostsTab" data-toggle="tab" href="#allPosts" role="tab" aria-controls="allPosts">All Posts</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" id="photosTab" data-toggle="tab" href="#photos" role="tab" aria-controls="photos">Photos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" id="videosTab" data-toggle="tab" href="#videos" role="tab" aria-controls="videos">Videos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" id="blogsTab" data-toggle="tab" href="#blogs" role="tab" aria-controls="blogs">Blogs</a>
              </li>
            </ul>
            <div class="select-container">
              <span class="label">Show on page</span>
              <select class="selectpicker" id="pageControlTabs">
                <option data-tokens="0" value="about">About</option>
                <option data-tokens="1" value="allPosts">All Posts</option>
                <option data-tokens="2" value="photos">Photos</option>
                <option data-tokens="3" value="videos">Videos</option>
                <option data-tokens="4" value="blogs">Blogs</option>
              </select>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render partial: 'main_container' %>