config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { sessions: 'users/sessions', :registrations => "users/registrations",
                                      :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    collection do
      get :news_feed
      get :profile
      get :search
    end
    member do
      post :upload_pic
      get :profile
    end
    resources :dream_garages, only: [:create, :destroy]
  end
  
  resources :companies do
    member do
      post :upload_pic 
    end
  end

  resources :groups do
    member do
      post :upload_pic 
    end
  end

  resources :events do
    member do
      post :attend
      post :drop
      post :join_request
      put :accept_request
      get :accept_invitation
      post :send_invitations
      post :upload_pic
    end
  end

  resources :motors do
    collection do
      get :look_up, constraints: { format: 'json' }
    end
    member do
      post :upload_pic
    end
  end

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :posts, only: [:create, :show] do
    member do
      post :like
      post :dislike
      post :create_comment
      post :add_reply
      post :like_comment
      post :dislike_comment
    end

    resource :comments, only: %i[destroy]
  end


  resources :settings, only: [] do
    collection do
      match '/account' => 'settings#account', via: [:get, :post]
      match '/privacy' => 'settings#privacy', via: [:get, :post]
      match '/notifications' => 'settings#notifications', via: [:get, :post]
      match '/security' => 'settings#security', via: [:get, :post]
    end
  end

  resources :utils, only: [] do
    collection do
      get :states_list
      get :cities_list
      get :location_search
    end
  end

  resources :follow, only: [] do
    collection do
      post :user
      post :unfollow_user
      post :motor
      post :unfollow_motor
      post :company
      post :unfollow_company
    end
  end

  resources :notifications, only: [:index] do

  end

  resource :search, controller: 'search', only: [] do
    collection do
      get :people
      get :companies
      get :motors
      get :groups
      get :events
    end
  end

  get '/publish/:type', to: 'posts#new', as: :publish_blog
  get '/news_feed', to: 'users#news_feed', as: :news_feed
  get '/profile', to: 'users#profile', as: :user_profile
end

app/views/shared/_blogs_tab.html.erb
<div class="tab-pane fade" id="blogs" role="tabpanel" aria-labelledby="blogsTab">
  <div class="main-container">
    <%= render partial: 'sidebar_container' %>
    <div class="content-container details mobile-order-2">
      <%= render partial: 'posts/index', locals: {posts: current_entity.blog_posts} %>
<!--       <div class="content-preloader">
        <span class="preloader"><img src="../assets/icons/i-spinner.svg" alt=""></span>
      </div> -->
    </div>
  </div>
</div>

app/views/shared/_flash_messages.html.erb
<% [:success, :notice, :error].each do |key| %>
  <% if flash[key].present? %>
    <div class="info">
      <div class="alert alert-<%= key %>">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <%= flash[key] %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_header.html.erb
<header class="header">
  <div class="container">
    <div class="row align-items-stretch">
      <div class="col-12 header-container">
        <%= render partial: 'shared/header_logo' %>
        <div class="search-container">
          <%= link_to companies_search_url, class: 'search-btn' do  %>
            <i class="zmdi zmdi-search"></i>
          <% end %>
<!--           <a href="http://motor.valeda.co/search_page.html" class="search-btn"><i class="zmdi zmdi-search"></i></a> -->
        </div> 
        <div class="nav-section hidden-sm-down">
          <%= render partial: 'shared/secondary_menu' %>
        </div>
        <div class="nav-section">
          <ul class="nav-menu">
            <li class="hidden-sm-down"><a href="#"><i class="zmdi zmdi-accounts-add i-big"></i></a></li>
            <%= render partial: 'shared/notifications_menu' %>
            <li class="hidden-sm-down">
              <div class="dropdown">
                <div class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <a href="#"><i class="zmdi zmdi-more-vert"></i></a>
                </div>
                <div class="dropdown-menu dropdown-menu-right profile-dropdown" aria-labelledby="dropdownMenuButton2">
                  <div class="dropdown-body">
                    <%= link_to 'My Profile', user_profile_path, class: 'dropdown-item' %>
                    <%= link_to 'Account settings', account_settings_path, class: 'dropdown-item' %>
                    <%= link_to 'Security', security_settings_path, class: 'dropdown-item' %>
                    <%= link_to 'Notification Settings', notifications_settings_path, class: 'dropdown-item' %>
                    <%= link_to 'Privacy settings', privacy_settings_path, class: 'dropdown-item' %>
                  </div>
                  <div class="dropdown-footer">
                    <%= link_to('Log out', destroy_user_session_path, method: :delete, class: 'dropdown-item') %>
                  </div>
                </div>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/shared/_header_logo.html.erb
<%= link_to root_path, class: 'navbar-brand' do %>
  <svg version="1.1" id="&#x421;&#x43B;&#x43E;&#x439;_1"
    xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="36px" height="36px" viewBox="0 0 100 100" style="enable-background:new 0 0 100 100;" xml:space="preserve">
    <g>
      <path style="fill:#FFFFFF;" d="M63.157,35.036H36.3l4.837,9.638l2.755,5.429l-2.473,5.082L36.3,65.693h27.409
        c1.654,0,2.645-0.505,3.383-1.139c0.749-0.631,0.918-1.846,0.918-3.254v-2.299c0-1.409-0.169-2.19-0.918-2.821
        c-0.738-0.631-1.73-0.706-3.383-0.706H51.23l2.473-4.439l-2.755-5.05h12.209c1.575,0,2.921-1.084,3.614-1.667
        c0.67-0.603,1.24-2.349,1.24-3.681v-2.225c0-1.335-0.569-2.094-1.24-2.694C66.078,35.133,64.731,35.036,63.157,35.036z"/>
      <path style="fill:#FFFFFF;" d="M88.743,0h-77.49C5.037,0,0,5.04,0,11.257v77.49C0,94.96,5.037,100,11.254,100h77.49
        C94.96,100,100,94.96,100,88.746v-77.49C100,5.04,94.96,0,88.743,0z M83.339,63.489c0,5.242-1.34,9.512-4.191,11.597
        c-2.868,2.09-8.005,3.746-15.591,3.746H17.398l14.665-28.101L17.398,22.628h46.536c6.82,0,11.691,0.855,14.452,2.796
        c2.763,1.938,4.223,5.118,4.223,9.805v3.561c0,3.104-0.851,5.507-2.366,7.189c-1.535,1.685-3.949,2.704-7.09,3.082
        c3.276,0.645,5.753,1.938,7.573,3.873c1.8,1.935,2.613,4.369,2.613,7.285V63.489z"/>
    </g>
  </svg>
<% end %>

app/views/shared/_mobile_menu.html.erb
<div class='mobile-menu'>
  <ul>
    <li>
      <a href='http://motor.valeda.co/login.html'><i class='ion-ios-home-outline'></i></a>
    </li>
    <li>
      <a href='http://motor.valeda.co/my_profile.html'><i class='ion-ios-person-outline'></i></a>
    </li>
    <li class='active'>
      <a href='http://motor.valeda.co/settings.html'><i class='ion-ios-gear-outline'></i></a>
    </li>
    <li>
      <%= render partial: 'shared/secondary_menu_dropdown' %>
    </li>
  </ul>
</div>

app/views/shared/_notifications_menu.html.erb
<li>
  <div class='dropdown'>
    <div class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <a href="#">
        <% if current_user.unread_notifications_count > 0 %>
          <span class="badge counter-badge"><%= current_user.unread_notifications_count %></span>
        <% end %>
        <i class="zmdi zmdi-notifications"></i>
      </a>
    </div>
    <div class="dropdown-menu dropdown-menu-right dropdown-notifications" aria-labelledby="dropdownNotificatioinButton">
      <div class="dropdown-header">
        <span class="title">Notifications</span>
        <% if current_user.unread_notifications_count > 0 %>
          <span class="info"><%= current_user.unread_notifications_count %> new notifications</span>
        <% end %>
      </div>
      <div class="dropdown-body">
        <div class="notifications-list">
          <% current_user.notifications[0..5].each do |notification| %>
            <%= render partial: get_notification_item(notification), locals: { notification: notification, args: notification.args, header: true } %>
          <% end %>
        </div>
      </div>
      <div class="dropdown-footer">
        <%= link_to notifications_path, class: 'btn btn-primary btn-block' do %>
          <span>View all</span>
        <% end %>
      </div>
    </div>
  </div>
</li>

app/views/shared/_photos_tab.html.erb
<div class="tab-pane fade" id="photos" role="tabpanel" aria-labelledby="photosTab">
  <div class="main-container">
    <div class="content-container full-width">
      <div class="content-block gallery-section images-gallery">
        <% photos.each do |photo| %>
          <a class="fancyimage" data-fancybox="gallery" href="<%= photo.file.url %>">
            <%= image_tag(photo.file.galary_thumb.url) %>
          </a>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_read_notes.html.erb
<div class='notes'>
  <div class='short-note'>
    <%= truncate(message.html_safe, length: 350, omission: '', escape: false) { link_to '...read more', '#', 'data-behavior': 'read_more'} %>
  </div>
  <div class='full-note hidden'>
    <%= message.html_safe %>
    <br/>
    <%= link_to 'read less', '#', 'data-behavior': 'read_less' %>
  </div>
</div>

app/views/shared/_secondary_menu.html.erb
<ul class="nav-menu secondary-menu">
  <li>
    <%= link_to(user_profile_path, class: 'profile-link-container') do %>
      <span class="avatar-container">
        <%= image_tag current_user.thumb_url, class: 'avatar-img', alt: current_user.display_name %>
      </span>
      <span class="user-name"><%= current_user.display_name %></span>
    <% end %>
  </li>
  <li>
    <%= link_to "<span>Newsfeed</span>".html_safe, news_feed_path %>
  </li>
  <li>
    <%= render partial: 'shared/secondary_menu_dropdown' %>
  </li>
</ul>

app/views/shared/_secondary_menu_dropdown.html.erb
<div class="dropdown">
  <div class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <a href="#"><i class="zmdi zmdi-more"></i></a>
  </div>
  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton1">
    <div class="dropdown-body">
      <%= link_to 'Create Company', new_company_path, class: 'dropdown-item' %>
      <%= link_to 'Create Event', new_event_path, class: 'dropdown-item' %>
      <%= link_to 'Create Group', new_group_path, class: 'dropdown-item' %>
      <%= link_to 'Create Motor', new_motor_path, class: 'dropdown-item' %>
    </div>
  </div>
</div>

app/views/shared/_share_page.html.erb
<div class="widget">
  <div class="widget-header">
    <span class="title with-icon"><i class="zmdi zmdi-share"></i>Share Profile</span>
  </div>
  <div class="widget-body">
    <ul class="socials-list">
      <li><a href="#"><span><i class="fa fa-facebook" aria-hidden="true"></i></span></a></li>
      <li><a href="#"><span><i class="fa fa-twitter" aria-hidden="true"></i></span></a></li>
      <li><a href="#"><span><i class="fa fa-google-plus" aria-hidden="true"></i></span></a></li>
      <li><a href="#"><span><i class="fa fa-whatsapp" aria-hidden="true"></i></span></a></li>
      <li><a href="#"><span><i class="fa fa-envelope" aria-hidden="true"></i></span></a></li>
    </ul>
  </div>
</div>

app/views/shared/_sidebar_footer.html.erb
<div class="sidebar-footer">
  <div class="license-menu-container">
    <ul class="license-menu">
      <li><a href="#">Terms of Use</a></li>
      <li><a href="#">Legal Terms</a></li>
      <li><a href="#">Privacy Policy</a></li>
    </ul>
  </div>
  <p class="copyright">© 2017 MotorBrag Ltd.</p>
</div>

app/views/shared/_videos_tab.html.erb
<div class="tab-pane fade" id="videos" role="tabpanel" aria-labelledby="videosTab">
  <div class="main-container">
      <div class="content-container full-width">
          <div class="content-block gallery-section videos-gallery">
              <div class="gallery-item">
                  <a class="fancyimage" data-fancybox="videoGallery1" href="https://vimeo.com/video/213944440?color=e51414&title=0&byline=0&portrait=0">
                      <img src="../assets/gallery-images/black-and-silver-cruiser-motorcycle-169701.jpg" alt="">
                      <span class="views-stats top left"><i class="zmdi zmdi-eye"></i>101 views</span>
                      <span class="views-stats top right"><i class="zmdi zmdi-time"></i>1m 23s</span>
                      <span class="play-btn">
                          <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="59" height="59" viewBox="0 0 59 59">
                            <defs>
                              <style>
                                .i-play {
                                    fill: #fff;
                                    fill-rule: evenodd;
                                    filter: url(#filterPlayBtn);
                                }
                              </style>
                              <filter id="filterPlayBtn" x="692" y="717" width="59" height="59" filterUnits="userSpaceOnUse">
                                <feOffset result="offset" dy="2" in="SourceAlpha"/>
                                <feGaussianBlur result="blur" stdDeviation="2.828"/>
                                <feFlood result="flood" flood-opacity="0.55"/>
                                <feComposite result="composite" operator="in" in2="blur"/>
                                <feBlend result="blend" in="SourceGraphic"/>
                              </filter>
                            </defs>
                            <path class="i-play" d="M729.367,744l-13-9.75v19.5ZM699,744a21.673,21.673,0,1,0,6.348-15.285A20.829,20.829,0,0,0,699,744Zm4.367,0a17.337,17.337,0,1,1,5.078,12.289A16.738,16.738,0,0,1,703.367,744Z" transform="translate(-692 -717)"/>
                          </svg>
                      </span>
                      <span class="overlay"></span>
                  </a>
                  <span class="title">Just discover the perfect road in Alaska</span>
                  <span class="date">27 February 2017</span>
              </div>
          </div>
      </div>
  </div>
</div>