config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { sessions: 'users/sessions', :registrations => "users/registrations",
                                      :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    collection do
      get :news_feed
      get :profile
      get :search
    end
    member do
      post :upload_pic
      get :profile
    end
    resources :dream_garages, only: [:create, :destroy]
  end
  
  resources :companies do
    member do
      post :upload_pic 
    end
  end

  resources :groups do
    member do
      post :upload_pic 
    end
  end

  resources :events do
    member do
      post :attend
      post :drop
      post :join_request
      put :accept_request
      get :accept_invitation
      post :send_invitations
      post :upload_pic
    end
  end

  resources :motors do
    collection do
      get :look_up, constraints: { format: 'json' }
    end
    member do
      post :upload_pic
    end
  end

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :posts, only: [:create, :show] do
    member do
      post :like
      post :dislike
      post :create_comment
      post :add_reply
      post :like_comment
      post :dislike_comment
    end

    resource :comments, only: %i[destroy]
  end


  resources :settings, only: [] do
    collection do
      match '/account' => 'settings#account', via: [:get, :post]
      match '/privacy' => 'settings#privacy', via: [:get, :post]
      match '/notifications' => 'settings#notifications', via: [:get, :post]
      match '/security' => 'settings#security', via: [:get, :post]
    end
  end

  resources :utils, only: [] do
    collection do
      get :states_list
      get :cities_list
      get :location_search
    end
  end

  resources :follow, only: [] do
    collection do
      post :user
      post :unfollow_user
      post :motor
      post :unfollow_motor
      post :company
      post :unfollow_company
    end
  end

  resources :notifications, only: [:index] do

  end

  resource :search, controller: 'search', only: [] do
    collection do
      get :people
      get :companies
      get :motors
      get :groups
      get :events
    end
  end

  get '/publish/:type', to: 'posts#new', as: :publish_blog
  get '/news_feed', to: 'users#news_feed', as: :news_feed
  get '/profile', to: 'users#profile', as: :user_profile
end

app/models/entities/motor.rb
class Motor < Entity

  MOTOR_CATEGORIES = %w(Car Bike Boat Plane Helicopter Other)
  MOTOR_MAKE = %w(Mercedes-Benz BMW AUDI VW Honda)

  field :motor_category, type: String
  field :reg_no, type: String
  field :make, type: String
  field :model, type: String
  field :make_year, type: String
  field :gearbox, type: String
  field :co2_emissions, type: String
  field :trim, type: String
  field :body_type, type: String
  field :fuel_type, type: String
  field :engine_size, type: String
  field :top_speed, type: String
  field :mileage, type: String
  field :acceleration, type: String
  field :fuel_consumption, type: String

  has_and_belongs_to_many :dream_garages
  has_and_belongs_to_many :followers, class_name: 'User', inverse_of: :following_motors

  scope :with_motor_category, ->(motor_category) { where(motor_category: motor_category) }
  scope :with_reg_no, ->(reg_no) { where(reg_no: reg_no) }
  scope :with_make, ->(make) { where(make: make) }
  scope :with_model, ->(model) { where(model: model) }
  scope :with_make_year, ->(make_year) { where(make_year: make_year) }
  scope :with_gearbox, ->(gearbox) { where(gearbox: gearbox) }
  scope :with_co2_emissions, ->(co2_emissions) { where(co2_emissions: co2_emissions) }
  scope :with_trim, ->(trim) { where(trim: trim) }
  scope :with_body_type, ->(body_type) { where(body_type: body_type) }
  scope :with_fuel_type, ->(fuel_type) { where(fuel_type: fuel_type) }
  scope :with_engine_size, ->(engine_size) { where(engine_size: engine_size) }
  scope :speed_between, -> (mn, mx) { where({ :top_speed.lte => mn, :top_speed.gte => mx }) }
  scope :with_top_speed, ->(top_speed) { where(top_speed: top_speed) }
  scope :with_mileage, ->(mileage) { where(mileage: mileage) }
  scope :with_acceleration, ->(acceleration) { where(acceleration: acceleration) }
  scope :with_fuel_consumption, ->(fuel_consumption) { where(fuel_consumption: fuel_consumption) }



  def self.vehicle_data_lookup(reg_no='AP10HCX')
    reg_no='AP10HCX'
    options = {
      v: 2,
      api_nullitems: 1,
      user_tag: nil,
      auth_apikey: ENV['UKV_API_KEY'],
      key_VRM: reg_no
    }
    response = HTTParty.get(UKV_API, query: options, timeout: 20)
    return default_data if !(response.try(:code) == 200 && response['Response']['StatusCode'].eql?('Success'))
    resp = JSON.parse(response.body)
    match_data(resp)
  end

  private

  def self.options_for(f)
    distinct(f).select(&:present?) 
  end

  def self.match_data(data)
    {
      make: data['Response']['DataItems']['VehicleRegistration']['Make'],
      model: data['Response']['DataItems']['VehicleRegistration']['Model'],
      make_year: data['Response']['DataItems']['VehicleRegistration']['YearOfManufacture'],
      gearbox: data['Response']['DataItems']['VehicleRegistration']['TransmissionType'],
      co2_emissions: data['Response']['DataItems']['VehicleRegistration']['Co2Emissions'],
      trim: data['Response']['DataItems']['ClassificationDetails']['Smmt']['Trim'],
      body_type: data['Response']['DataItems']['SmmtDetails']['BodyStyle'],
      fuel_type: data['Response']['DataItems']['SmmtDetails']['FuelType'],
      engine_size: data['Response']['DataItems']['SmmtDetails']['NominalEngineCapacity'].to_f,
      top_speed: data['Response']['DataItems']['TechnicalDetails']['Performance']['MaxSpeed']['Mph'],
      acceleration: data['Response']['DataItems']['TechnicalDetails']['Performance']['Acceleration']['Mph'],
      fuel_consumption: data['Response']['DataItems']['TechnicalDetails']['Consumption']['Combined']['Mpg'],
      mileage: data['Response']['DataItems']['VehicleHistory']['Mileage'].to_f
    }
  end

  def self.default_data
    {
      make: 'Any',
      model: 'Any',
      make_year: 'Any',
      gearbox: 'Any',
      co2_emissions: 'Any',
      trim: 'Any',
      body_type: 'Any',
      engine_size: 'Any',
      top_speed: 'Any',
      mileage: 'Any',
      acceleration: 'Any',
      fuel_consumption: 'Any'
    }
  end
end

app/controllers/motors_controller.rb
class MotorsController < ApplicationController
  before_action :get_motor, only: [:show, :upload_pic, :edit, :update]

  def new
  end

  def upload_pic
    if @motor.update_attributes(motor_pic_attrs)
      flash[:success] = "Updated pic successfully"
    else
      flash[:error] = "Failed to update pic"
    end
    redirect_to motor_path(@motor)
  end

  def create
    motor = current_user.motors.build(motor_attrs)
    if motor.save
      flash[:success] = 'Motor Created successfully'
      set_current_entity(motor)
      redirect_to motor_path(motor)
    else
      render_with_error(motor.errors.full_messages.join(','), 422)
    end
  end

  def edit
    set_current_entity(@motor)
  end

  def update
    if @motor.update_attributes(motor_attrs)
      flash[:success] = "Updated profile successfully"
    else
      flash[:error] = "Failed to update profile"
    end
    redirect_to motor_path(@motor)
  end

  def show
    set_current_entity(@motor)
  end

  def look_up
    # data = Motor.vehicle_data_lookup(params[:reg_no])
    data = Motor.vehicle_data_lookup
    render json: data.to_json
  end

  private

  def motor_attrs
    params.require(:motor).permit(:motor_category, :reg_no,
      :make, :model, :make_year, :gearbox, :co2_emissions, 
      :trim, :body_type, :engine_size, :top_speed, :mileage,
      :acceleration, :fuel_consumption, :fuel_type,
      profile_attributes: [:name, :about, :avatar, :cover_pic],
      photos_attributes: [:id, :file, :_destroy]
    )
  end

  def motor_pic_attrs
    params.require(:motor).permit(
      profile_attributes: [:cover_pic, :avatar]
    )
  end

  def get_motor
    @motor ||= Motor.find(params[:id])
  end
end

app/helpers/motor_helper.rb
module MotorHelper

  def prepare_select_field(name, values=[])
    label_tag = content_tag(:label, for: "motor#{name.camelize}") { name.humanize.titleize }
    select_tag = content_tag(:select, id: "motor#{name.camelize}", name: "motor[#{name}]", class: 'selectpicker', prompt: "Select #{name.humanize.titleize}") do
      options = [content_tag(:option, value: nil) { "Select #{name.humanize.titleize}" }]
      values.each do |value|
        options << content_tag(:option, value: value) { value }
      end
      options.join.html_safe
    end
    line_break = content_tag(:div, nil, class: 'form-control-border')
    content_tag(:div, class: 'col-md-4 col-xs-12') do
      content_tag(:div, class: 'form-group') do
        (label_tag + select_tag + line_break).html_safe
      end
    end
  end

  def in_dreamgarage?(user, motor)
    user.dream_garage.motors.where(id: motor.id.to_s).first.present?
  end
end

app/views/motors/_about.html.erb
<div class="tab-pane fade" id="about" role="tabpanel" aria-labelledby="aboutTab">
  <div class="main-container">
    <%= render partial: 'sidebar_container' %>
    <div class="content-container mobile-order-1">
      <%= render partial: 'motor_description', locals: { parent: 'about' } %>
    </div>
  </div>
</div>

app/views/motors/_sidebar_container.html.erb
<div class="sidebar-container mobile-order-2">
  <%= render partial: 'shared/share_page' %>
  <%= render partial: 'privacy' %>
  <%= render partial: 'events/index' %>
  <%= render partial: 'followers' %>
  <%= render partial: 'shared/sidebar_footer' %>
</div>

app/views/motors/edit.html.erb
<%= form_tag(motor_path(@motor), method: :put, multipart: true, class: 'form content-form', id: 'edit_motor', remote: true) do %>
  <%= render partial: 'entities/cover_pic_container', locals: { type: 'motor', current: @motor } %>
  <div class='container error'></div>

  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="main-container">
          <div class="content-container">
            <div class="content-block">
              <div class="block-header">
                <h4>Motor Details</h4>
              </div>
              <div class="block-body">
                <div class="row">
                  <div class="col-md-12">
                    <div class="form-group">
                      <label for="motorCategory">Motor category</label>
                      <%= select_tag "motor[motor_category]", options_for_select(Motor::MOTOR_CATEGORIES, @motor.motor_category), id: 'motorCategory', class: 'selectpicker' %>
                      <div class="form-control-border"></div>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <div class="form-group">
                      <label for="motorCategory">Motor Reg number</label>
                      <div class="row">
                        <div class="col-md-6 col-sm-12">
                          <div class="registration-number-container">
                            <div class="country-section">
                              <span>
                                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="13" height="14" viewBox="0 0 950 943">
                                </svg>
                              </span>
                              <span>GB</span>
                            </div>
                            <div class="input-field">
                              <input type="text" name='motor[reg_no]' value="<%= @motor.reg_no %>" class="form-control" placeholder="W12T P0W3R" data-behavior='fetch_motor_data' data-url="<%= look_up_motors_path %>"/>
                            </div>
                          </div>
                        </div>
                        <div class="col-md-6 col-sm-12">
                          <span class="description"><span>NOTE:</span> Enter UK registration number or manually select categories.</span>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6 col-xs-12">
                    <div class="form-group">
                      <label for="motorMake">Make</label>
                      <%= select_tag "motor[make]", options_for_select(Motor::MOTOR_MAKE, @motor.make), id: 'motorMake', class: 'selectpicker' %>
                      <div class="form-control-border"></div>
                    </div>
                  </div>
                  <div class="col-md-6 col-xs-12">
                    <div class="form-group">
                      <label for="motorModel">Model</label>
                      <%= select_tag "motor[model]", options_for_select(Motor.options_for(:model), @motor.model), id: 'motorModel', class: 'selectpicker' %>
                      <div class="form-control-border"></div>
                    </div>
                  </div>

                  <div class="col-md-4 col-xs-12">
                    <div class="form-group">
                      <label for="motorTrim">Trim</label>
                      <%= select_tag "motor[trim]", options_for_select(Motor.options_for(:trim), @motor.trim), id: 'motorTrim', class: 'selectpicker'  %>
                      <div class="form-control-border"></div>
                    </div>
                  </div>

                  <div class="col-md-4 col-xs-12">
                    <div class="form-group">
                      <label for="motorBodyType">Body Type</label>
                      <%= select_tag "motor[body_type]", options_for_select(Motor.options_for(:body_type), @motor.body_type), id: 'motorBodyType', class: 'selectpicker'  %>
                      <div class="form-control-border"></div>
                    </div>
                  </div>

                  <div class="col-md-4 col-xs-12">
                    <div class="form-group">
                      <label for="motorMakeYear">Make Year</label>
                        <%= select_tag "motor[make_year]", options_for_select(Motor.options_for(:make_year), @motor.make_year), id: 'motorMakeYear', class: 'selectpicker'  %>
                      <div class="form-control-border"></div>
                    </div>
                  </div>

                  <div class="col-md-4 col-xs-12">
                    <div class="form-group">
                      <label for="motorMileage">Mileage</label>
                         <%= select_tag "motor[mileage]", options_for_select(Motor.options_for(:mileage), @motor.mileage), id: 'motorMileage', class: 'selectpicker'  %>               
                      <div class="form-control-border"></div>
                    </div>
                  </div>

                  <div class="col-md-4 col-xs-12">
                    <div class="form-group">
                      <label for="motorEngineSize">Engine Size</label>
                      <%= select_tag "motor[engine_size]", options_for_select(Motor.options_for(:engine_size), @motor.engine_size), id: 'motorEngineSize', class: 'selectpicker'  %>
                      <div class="form-control-border"></div>
                    </div>
                  </div>

                  <div class="col-md-4 col-xs-12">
                    <div class="form-group">
                      <label for="motorFuelType">Fuel Type</label>
                      <%= select_tag "motor[fuel_type]", options_for_select(Motor.options_for(:fuel_type), @motor.fuel_type), id: 'motorFuelType', class: 'selectpicker'  %>
                      <div class="form-control-border"></div>
                    </div>
                  </div>

                  <div class="col-md-4 col-xs-12">
                    <div class="form-group">
                      <label for="motorAcceleration">Acceleration</label>
                      <%= select_tag "motor[acceleration]", options_for_select(Motor.options_for(:acceleration), @motor.acceleration), id: 'motorAcceleration', class: 'selectpicker'  %>
                      <div class="form-control-border"></div>
                    </div>
                  </div>


                  <div class="col-md-4 col-xs-12">
                    <div class="form-group">
                      <label for="motorTopSpeed">Top Speed</label>
                      <%= select_tag "motor[top_speed]", options_for_select(Motor.options_for(:top_speed), @motor.top_speed), id: 'motorTopSpeed', class: 'selectpicker'  %>
                      <div class="form-control-border"></div>
                    </div>
                  </div>


                  <div class="col-md-4 col-xs-12">
                    <div class="form-group">
                      <label for="motorCo2Emissions">CO2 Emissions</label>
                      <%= select_tag "motor[co2_emissions]", options_for_select(Motor.options_for(:co2_emissions), @motor.co2_emissions), id: 'motorCo2Emissions', class: 'selectpicker'  %>
                      <div class="form-control-border"></div>
                    </div>
                  </div>

                  <div class="col-md-4 col-xs-12">
                    <div class="form-group">
                      <label for="motorFuelConsumption">Fuel Consumption</label>
                      <%= select_tag "motor[fuel_consumption]", options_for_select(Motor.options_for(:fuel_consumption), @motor.fuel_consumption), id: 'motorFuelConsumption', class: 'selectpicker'  %>
                      <div class="form-control-border"></div>
                    </div>
                  </div>                  

                  <div class="col-md-4 col-xs-12">
                    <div class="form-group">
                      <label for="motorGearbox">Gearbox</label>
                      <%= select_tag "motor[gearbox]", options_for_select(Motor.options_for(:gearbox), @motor.gearbox), id: 'motorGearbox', class: 'selectpicker'  %>
                      <div class="form-control-border"></div>
                    </div>
                  </div>                  
                  
                  
                  

                </div>
              </div>
              <div class="tags-container">
                <ul class="tags-list">
                  <li class="tag">
                    <span>Mercedes-benz CLK</span>
                    <a href="#" class="remove-btn">
                      <i class="zmdi zmdi-close"></i>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="content-block">
              <%= render partial: 'entities/upload_photos_and_videos_section', locals: { type: 'motor' } %>
            </div>
            <div class="content-block">
              <div class="block-header">
                <h4>Aditional Details</h4>
              </div>
              <div class="block-body">
                <span class="description">Motor description</span>
                <div class="form-group">
                  <textarea name="motor[profile_attributes][about]" id="motorDescription" cols="30" rows="4" class="form-control">
                    <%= @motor.about %>
                  </textarea>
                  <span class="form-control-border"></span>
                </div>
              </div>
            </div>
            <div class="buttons-block">
              <div class='hidden_images hidden'></div>
              <%= submit_tag "Update motor", class: 'btn btn-primary btn-block' %>
            </div>
          </div>
          <%= render partial: 'sidebar_nav' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/motors/new.html.erb
<%= form_tag(motors_path, method: :post, multipart: true, class: 'form content-form', id: 'new_motor', remote: true) do %>
  <%= render partial: 'entities/cover_pic_container', locals: { type: 'motor', current: nil } %>
  <div class='container error'></div>

  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="main-container">
          <div class="content-container">
            <div class="content-block">
              <div class="block-header">
                <h4>Motor Details</h4>
              </div>
              <div class="block-body">
                <div class="row">
                  <div class="col-md-12">
                    <div class="form-group">
                      <label for="motorCategory">Motor category</label>
                      <%= select_tag "motor[motor_category]", options_for_select(Motor::MOTOR_CATEGORIES, Motor::MOTOR_CATEGORIES.first), id: 'motorCategory', class: 'selectpicker' %>
                      <div class="form-control-border"></div>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <div class="form-group">
                      <label for="motorCategory">Motor Reg number</label>
                      <div class="row">
                        <div class="col-md-6 col-sm-12">
                          <div class="registration-number-container">
                            <div class="country-section">
                              <span>
                                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="13" height="14" viewBox="0 0 950 943">
                                </svg>
                              </span>
                              <span>GB</span>
                            </div>
                            <div class="input-field">
                              <input type="text" name='motor[reg_no]' class="form-control" placeholder="W12T P0W3R" data-behavior='fetch_motor_data' data-url="<%= look_up_motors_path %>"/>
                            </div>
                          </div>
                        </div>
                        <div class="col-md-6 col-sm-12">
                          <span class="description"><span>NOTE:</span> Enter UK registration number or manually select categories.</span>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-6 col-xs-12">
                    <div class="form-group">
                      <label for="motorMake">Make</label>
                      <%= select_tag "motor[make]", options_for_select(Motor::MOTOR_MAKE), id: 'motorMake', class: 'selectpicker', prompt: 'Select Make' %>
                      <div class="form-control-border"></div>
                    </div>
                  </div>
                  <div class="col-md-6 col-xs-12">
                    <div class="form-group">
                      <label for="motorModel">Model</label>
                      <%= select_tag "motor[model]", options_for_select([]), id: 'motorModel', class: 'selectpicker', prompt: 'Select Model' %>
                      <div class="form-control-border"></div>
                    </div>
                  </div>
                  <%= prepare_select_field('trim') %>
                  <%= prepare_select_field('body_type') %>
                  <%= prepare_select_field('make_year') %>
                  <%= prepare_select_field('mileage') %>
                  <%= prepare_select_field('engine_size') %>
                  <%= prepare_select_field('fuel_type') %>
                  <%= prepare_select_field('acceleration') %>
                  <%= prepare_select_field('top_speed') %>
                  <%= prepare_select_field('co2_emissions') %>
                  <%= prepare_select_field('fuel_consumption') %>
                  <%= prepare_select_field('gearbox') %>
                </div>
              </div>
              <div class="tags-container">
                <ul class="tags-list">
                  <li class="tag">
                    <span>Mercedes-benz CLK</span>
                    <a href="#" class="remove-btn">
                      <i class="zmdi zmdi-close"></i>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="content-block">
              <%= render partial: 'entities/upload_photos_and_videos_section', locals: { type: 'motor' } %>
            </div>
            <div class="content-block">
              <div class="block-header">
                <h4>Aditional Details</h4>
              </div>
              <div class="block-body">
                <span class="description">Motor description</span>
                <div class="form-group">
                  <textarea name="motor[profile_attributes][about]" id="motorDescription" cols="30" rows="4" class="form-control">
                  </textarea>
                  <span class="form-control-border"></span>
                </div>
              </div>
            </div>
            <div class="buttons-block">
              <div class='hidden_images hidden'></div>
              <%= submit_tag "Post motor", class: 'btn btn-primary btn-block' %>
            </div>
          </div>
          <%= render partial: 'sidebar_nav' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/motors/show.html.erb
<div class="cover-image-container">
  <div class="cover-image-wrapper" style="background-image: url('<%= @motor.cover_pic.url %>')">
    <div class="overlay"></div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="profile-page-heading"> 
          <div class="user-profile-info">
            <% if @motor.user == current_user %>
              <%= link_to edit_motor_path(@motor) do %>
                <span class="btn btn-primary" style="position: absolute; left: 0; top: -105px;">EDIT PROFILE</span>
              <% end %>
              <%= form_tag(upload_pic_motor_path(@motor), method: :post, multipart: true, class: 'form content-form') do %>
                <%= file_field_tag "motor[profile_attributes][cover_pic]", class: 'hidden', id: "motor_cover_pic", 'data-behavior': 'submit_form' %>
                  <label for='motor_cover_pic'>
                    <span class="change-cover-image-btn btn btn-primary">
                      <span>Change cover</span>
                    </span>
                  </label>
              <% end %>
            <% end %>            
            <div class="avatar-container">
              <%= image_tag(@motor.avatar.thumb.url, class: 'avatar-img') %>
              <% if @motor.user == current_user %>
                <%= form_tag(upload_pic_motor_path(@motor), method: :post, multipart: true, class: 'form content-form') do %>
                  <%= file_field_tag "motor[profile_attributes][avatar]", class: 'hidden', 'data-behavior': 'submit_form', id: 'motor_profile_pic' %>
                  <label for='motor_profile_pic'>
                    <span class="add-avatar">
                      <i class="zmdi zmdi-camera-add"></i>
                    </span>
                  </label>
                <% end %>
              <% end %> 
            </div>
            <div class="profile-info">
              <span class="user-name"><%= @motor.name %></span>
              <span class="badge badge-car"><%= @motor.body_type %> Vehicle</span>
              <% unless current_user.motors.include?(@motor) %>
                <% if in_dreamgarage?(current_user, @motor) %>
                  <%= link_to user_dream_garage_path(user_id: current_user.id, motor_id: @motor.id), method: :delete do %>
                    <i class="zmdi zmdi-minus-circle-outline"></i>Remove from Dream Garage
                  <% end %>
                <% else %>
                  <%= link_to user_dream_garages_path(user_id: current_user.id, motor_id: @motor.id), method: :post do %>
                    <i class="zmdi zmdi-plus-circle-o"></i>Add to Dream Garage
                  <% end %>
                <% end %>
              <% end %>
            </div>
            <div class="profile-stats">
              <ul class="stats-list">
                <li>
                  <span class="stats-counter"><%= @motor.followers.count %></span>
                  <span class="stats-title">Followers</span>
                </li>
                <li>
                  <span class="stats-counter">0</span>
                  <span class="stats-title">Page Views</span>
                </li>
                <li>
                  <span class="stats-counter">0</span>
                  <span class="stats-title">Posts</span>
                </li>
                <li>
                  <span class="stats-counter">0</span>
                  <span class="stats-title">Photos</span>
                </li>
              </ul>
            </div>
            <div class="profile-buttons">
              <% if @motor.user == current_user %>
                <a href="#" class="btn btn-primary"><span>Followers</span></a>
              <% elsif current_user.follow_motor?(@motor) %>
                <%= link_to unfollow_motor_follow_index_path(id: @motor.id), method: :post, class: 'btn btn-primary' do %>
                  <span>UnFollow motor</span>
                <% end %>
              <% else %>
                <%= link_to motor_follow_index_path(id: @motor.id), method: :post, class: 'btn btn-primary' do %>
                  <span>Follow motor</span>
                <% end %>
              <% end %>
              <%= link_to profile_user_path(@motor.user), class: 'btn btn-secondary' do %>
                <span>Owner profile</span>
              <% end %>
            </div>
          </div>
            <div class="tabs-container page-control-tabs">
              <ul class="nav nav-tabs content-tabs justify-content-center" id="NewsfeedTab" role="tablist">
                <li class="nav-item">
                  <a class="nav-link" id="aboutTab" data-toggle="tab" href="#about" role="tab" aria-controls="about" aria-expanded="true">About</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" id="allPostsTab" data-toggle="tab" href="#allPosts" role="tab" aria-controls="allPosts">All Posts</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" id="photosTab" data-toggle="tab" href="#photos" role="tab" aria-controls="photos">Photos</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" id="videosTab" data-toggle="tab" href="#videos" role="tab" aria-controls="videos">Videos</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" id="blogsTab" data-toggle="tab" href="#blogs" role="tab" aria-controls="blogs">Blogs</a>
                </li>
              </ul>
              <div class="select-container">
                <span class="label">Show on page</span>
                <select class="selectpicker" id="pageControlTabs">
                  <option data-tokens="0" value="about">About</option>
                  <option data-tokens="1" value="allPosts">All Posts</option>
                  <option data-tokens="2" value="photos">Photos</option>
                  <option data-tokens="3" value="videos">Videos</option>
                  <option data-tokens="4" value="blogs">Blogs</option>
                </select>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render partial: 'main_container' %>